(function(){
  var WAKE_KEY='rehabWakeLockEnabled';
  var wakeLock=null;
  var selectedCheckinDate=dateKey();
  function dateFromKey(key){var p=String(key||dateKey()).split('-').map(Number);return new Date(p[0],p[1]-1,p[2])}
  function weekForDate(key){var start=parseLocalDate(data.start||def.start),d=dateFromKey(key),startDay=new Date(start.getFullYear(),start.getMonth(),start.getDate()),target=new Date(d.getFullYear(),d.getMonth(),d.getDate());return Math.max(1,Math.min(20,Math.floor((target-startDay)/604800000)+1))}
  function selectedInfo(){var d=dateFromKey(selectedCheckinDate),week=weekForDate(selectedCheckinDate),day=d.getDay(),code=dkey[day],key=schedule(week)[code]||'rest';return {date:selectedCheckinDate,week:week,dayIndex:day,day:days[day],code:code,key:key,workout:W[key]?W[key][0]:W.rest[0]}}
  function doneRecords(){return Object.values(data.records||{}).filter(function(r){return r&&r.done}).sort(function(a,b){return b.date.localeCompare(a.date)})}
  function checkinStreak(){var n=0,d=new Date(),today=data.records[dateKey(d)];if(!today||!today.done)d.setDate(d.getDate()-1);while(true){var r=data.records[dateKey(d)];if(!r||!r.done)break;n++;d.setDate(d.getDate()-1)}return n}
  function monthCount(){var p=dateKey().slice(0,7);return doneRecords().filter(function(r){return r.date.slice(0,7)===p}).length}
  function completedExercises(){var info=selectedInfo(),ids=(W[info.key]&&W[info.key][2])||[],k=info.week+'-'+info.code+'-'+info.date,checks=(data.checks&&data.checks[k])||{};return {done:ids.filter(function(id){return !!checks[id]}).length,total:ids.length}}
  function safeText(v){return String(v||'').replace(/[&<>"']/g,function(ch){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]})}
  function renderRecent(){var root=document.getElementById('checkinRecent');if(!root)return;var arr=doneRecords().slice(0,10);if(!arr.length){root.innerHTML='<div class="checkin-empty">还没有打卡记录。完成训练后选择对应日期，再点击“一键打卡”。</div>';return}root.innerHTML=arr.map(function(r){var md=r.date.slice(5).split('-');return '<button type="button" class="checkin-item" data-checkin-date="'+safeText(r.date)+'"><div class="checkin-day"><b>'+md[1]+'</b>'+md[0]+'月</div><div class="checkin-item-title">'+safeText(r.workout||'康复训练')+'<div class="sub">'+safeText(r.day||'')+' · 第'+safeText(r.week||'-')+'周</div></div><span class="checkin-badge">已打卡</span></button>'}).join('');root.querySelectorAll('[data-checkin-date]').forEach(function(btn){btn.onclick=function(){setSelectedDate(btn.getAttribute('data-checkin-date'))}})}
  function updateSummary(){var total=doneRecords().length,st=checkinStreak();var a=document.getElementById('checkinStreak');if(a)a.textContent=st+'天';var b=document.getElementById('checkinTotal');if(b)b.textContent=total+'次';var c=document.getElementById('checkinMonth');if(c)c.textContent=monthCount()+'次';var m=document.getElementById('mDone');if(m)m.textContent=total+'次';var s=document.getElementById('mStreak');if(s)s.textContent=st+'天'}
  function setSelectedDate(key){var today=dateKey();if(!key)key=today;if(key>today)key=today;selectedCheckinDate=key;var input=document.getElementById('checkinDateInput');if(input)input.value=key;renderCheckinState()}
  function renderCheckinState(){var info=selectedInfo(),r=data.records[info.date],done=!!(r&&r.done),progress=completedExercises(),isToday=info.date===dateKey();var dateEl=document.getElementById('checkinDate');if(dateEl)dateEl.textContent=info.date+' · '+info.day+' · 第'+info.week+'周';var workoutEl=document.getElementById('checkinWorkout');if(workoutEl)workoutEl.textContent=info.workout;var p=document.getElementById('checkinProgress');if(p)p.textContent=progress.total?'该日期动作已勾选 '+progress.done+'/'+progress.total+' 项。未全部勾选也可以打卡。':'完成该日期安排后即可打卡。';var label=document.getElementById('checkinSelectedLabel');if(label)label.textContent=isToday?'今天':'所选锻炼日';var status=document.getElementById('checkinStatus');if(status){status.className='checkin-status'+(done?' done':'');status.innerHTML='<span class="checkin-dot"></span>'+(done?'该日期已经打卡':'该日期还没有打卡')}var btn=document.getElementById('checkinBtn');if(btn){btn.textContent=done?'该日期已打卡':'完成训练，一键打卡';btn.disabled=done}var undo=document.getElementById('undoCheckinBtn');if(undo){undo.hidden=!done;undo.textContent='取消该日期打卡'}updateSummary();renderRecent()}
  function doCheckin(){var info=selectedInfo(),old=data.records[info.date]||{};data.records[info.date]=Object.assign({},old,{date:info.date,week:info.week,day:info.day,workout:info.workout,done:true,checkin:true,checkinAt:new Date().toLocaleString(),updated:new Date().toLocaleString()});saveData();renderCheckinState();if(typeof renderCalendar==='function')renderCalendar();if(navigator.vibrate)navigator.vibrate(90)}
  function undoCheckin(){var info=selectedInfo(),r=data.records[info.date];if(!r)return;if(!confirm('取消 '+info.date+' 的打卡？'))return;var hasDetail=(r.note&&r.note.trim())||(r.flags&&r.flags.length)||(r.before&&Object.keys(r.before).length)||(r.after&&Object.keys(r.after).length);if(hasDetail){r.done=false;r.checkin=false;r.updated=new Date().toLocaleString()}else delete data.records[info.date];saveData();renderCheckinState();if(typeof renderCalendar==='function')renderCalendar()}
  function wakeSupported(){return 'wakeLock' in navigator}
  function setWakeStatus(text,active){document.querySelectorAll('[data-wake-status]').forEach(function(el){el.textContent=text;el.classList.toggle('active',!!active)});document.querySelectorAll('[data-wake-toggle]').forEach(function(btn){btn.textContent=active?'关闭屏幕常亮':'开启屏幕常亮';btn.classList.toggle('green',!!active)})}
  async function requestWake(){if(!wakeSupported()){setWakeStatus('当前浏览器不支持屏幕常亮',false);return false}try{if(wakeLock)return true;wakeLock=await navigator.wakeLock.request('screen');setWakeStatus('屏幕常亮已开启',true);wakeLock.addEventListener('release',function(){wakeLock=null;if(localStorage.getItem(WAKE_KEY)==='1')setWakeStatus('常亮已暂停，点按可重新开启',false);else setWakeStatus('屏幕常亮已关闭',false)});return true}catch(e){wakeLock=null;setWakeStatus('无法开启，请保持页面前台并再次点按',false);return false}}
  async function releaseWake(){try{if(wakeLock)await wakeLock.release()}catch(e){}wakeLock=null;setWakeStatus('屏幕常亮已关闭',false)}
  async function toggleWake(){var enabled=localStorage.getItem(WAKE_KEY)==='1';if(enabled&&wakeLock){localStorage.removeItem(WAKE_KEY);await releaseWake();return}if(enabled&&!wakeLock){await requestWake();return}localStorage.setItem(WAKE_KEY,'1');var ok=await requestWake();if(!ok&&!wakeSupported())localStorage.removeItem(WAKE_KEY)}
  function wakePanel(){return '<div class="wake-panel"><div class="wake-copy"><b>训练时保持屏幕常亮</b><p>开启后，训练和计时期间屏幕不会自动熄灭。离开页面或系统限制时可能暂停。</p></div><div class="wake-control"><span class="wake-status" data-wake-status>屏幕常亮已关闭</span><button class="btn primary" type="button" data-wake-toggle>开启屏幕常亮</button></div></div>'}
  function compatibilityNodes(){return '<div class="checkin-compat" hidden><input id="done" type="checkbox"><div id="beforeScores"></div><div id="afterScores"></div><div id="flags"></div><textarea id="note"></textarea><div id="history"></div></div>'}
  function datePicker(){return '<div class="checkin-date-picker"><label for="checkinDateInput">选择锻炼日期</label><div class="checkin-date-controls"><input class="search" id="checkinDateInput" type="date" max="'+dateKey()+'"><button class="btn" type="button" id="checkinTodayBtn">今天</button><button class="btn" type="button" id="checkinYesterdayBtn">昨天</button></div><p>凌晨补练时，可以选择昨天；也可以补打更早的训练日期。</p></div>'}
  function buildCheckin(){var root=document.getElementById('record');if(!root)return;root.innerHTML='<h2>每日打卡</h2><p class="sub">自由选择实际锻炼日期，完成后点击一键打卡。</p><div class="checkin-layout"><section class="checkin-card">'+datePicker()+'<div class="checkin-label" id="checkinSelectedLabel">今天</div><div class="checkin-date" id="checkinDate"></div><div class="checkin-workout" id="checkinWorkout"></div><p class="checkin-progress" id="checkinProgress"></p><div class="checkin-status" id="checkinStatus"><span class="checkin-dot"></span>该日期还没有打卡</div><div class="checkin-actions"><button class="btn green checkin-main-btn" id="checkinBtn">完成训练，一键打卡</button><button class="btn" id="undoCheckinBtn" hidden>取消该日期打卡</button></div><div class="checkin-safety">出现刺痛、麻木、放射痛、关节卡住或明显无力时，不要为了打卡继续硬练，应暂停训练并视情况就医。</div>'+wakePanel()+'</section><section class="checkin-card"><h3>打卡概览</h3><div class="checkin-summary"><div class="checkin-stat"><b id="checkinStreak">0天</b><span>连续打卡</span></div><div class="checkin-stat"><b id="checkinMonth">0次</b><span>本月打卡</span></div><div class="checkin-stat"><b id="checkinTotal">0次</b><span>累计打卡</span></div></div><h3>最近打卡</h3><div class="checkin-history" id="checkinRecent"></div><div class="checkin-backup"><button class="btn" id="checkinExport">导出备份</button><label class="btn">导入备份<input id="checkinImport" type="file" accept="application/json" hidden></label><button class="btn red" id="checkinClear">清空全部数据</button></div></section></div>'+compatibilityNodes();var input=document.getElementById('checkinDateInput');input.value=selectedCheckinDate;input.min=data.start||def.start;input.onchange=function(){setSelectedDate(input.value)};document.getElementById('checkinTodayBtn').onclick=function(){setSelectedDate(dateKey())};document.getElementById('checkinYesterdayBtn').onclick=function(){var d=new Date();d.setDate(d.getDate()-1);setSelectedDate(dateKey(d))};document.getElementById('checkinBtn').onclick=doCheckin;document.getElementById('undoCheckinBtn').onclick=undoCheckin;document.getElementById('checkinExport').onclick=exportJSON;document.getElementById('checkinImport').onchange=function(e){importJSON(e);setTimeout(renderCheckinState,350)};document.getElementById('checkinClear').onclick=clearData;root.querySelectorAll('[data-wake-toggle]').forEach(function(btn){btn.onclick=toggleWake});renderCheckinState()}
  function addTimerWakePanel(){var panel=document.getElementById('timer');if(!panel||panel.querySelector('.wake-panel'))return;var wrap=document.createElement('div');wrap.innerHTML=wakePanel();panel.insertBefore(wrap.firstChild,panel.querySelector('.timer'));panel.querySelectorAll('[data-wake-toggle]').forEach(function(btn){btn.onclick=toggleWake})}
  function renameUI(){if(typeof tabs!=='undefined'&&tabs[2])tabs[2][1]='每日打卡';var open=document.getElementById('openRecordBtn');if(open)open.textContent='完成后打卡';var a=document.getElementById('mStreak');if(a&&a.nextElementSibling)a.nextElementSibling.textContent='连续打卡';var b=document.getElementById('mDone');if(b&&b.nextElementSibling)b.nextElementSibling.textContent='累计打卡';if(typeof renderNav==='function')renderNav()}
  function installCompatibility(){try{var originalTop=renderTop;renderTop=function(){originalTop();updateSummary()}}catch(e){}try{loadTodayForm=function(){renderCheckinState()}}catch(e){}try{renderHistory=function(){renderRecent()}}catch(e){}}
  document.addEventListener('visibilitychange',function(){if(document.visibilityState==='visible'&&localStorage.getItem(WAKE_KEY)==='1')requestWake()});window.addEventListener('pagehide',function(){if(wakeLock)wakeLock.release().catch(function(){})});
  setTimeout(function(){installCompatibility();renameUI();buildCheckin();addTimerWakePanel();if(localStorage.getItem(WAKE_KEY)==='1')requestWake()},250);
})();